version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/*
    schedule:
      interval: daily
    groups:
      codeql:
        patterns:
          - github/codeql-action/*
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
